name: 'Docker build action'
description: 'Odyssey docker build image action'
inputs:
  image-name:
    description: "Name of the docker image, defaults to git repository name"
    required: true
    default: ${{ github.event.repository.name }}
  registry-server:
    description: "Docker registry location/URL"
    required: true
  registry-user:
    description: "Docker registry username"
    required: true
  registry-pass:
    description: "Docker registry password"
    required: true
  npm-token:
    required: false
    description: "Access token for private (npm) packages."
  backfeed-repo-token:
    required: false
    description: "Github token to passthrough docker build to access current repo"
outputs:
  version:
    description: "Version string generated for the image."
    value: ${{ steps.setvars.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: setvars
      name: ${{github.event_name}}-${{github.event.ref }}
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "schedule" ]; then
          VERSION=nightly
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
            VERSION=latest
          fi
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          VERSION=pr-${{ github.event.number }}
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "::set-output name=version::$(echo $VERSION)"

    # checkout the repo
    - name: "Checkout GitHub Action"
      uses: actions/checkout@master
      with:
        submodules: true
        lfs: true

    - name: "Docker login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.registry-server }}
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-pass }}

    - name: "Github packages authorization"
      uses: actions/setup-node@v2
      with:
        registry-url: 'https://npm.pkg.github.com'
        scope: '@OdysseyMomentumExperience'
        token: ${{ inputs.npm-token }}

    - name: "Build and push image"
      env:
        IMAGE: ${{ inputs.registry-server }}/${{ inputs.image-name }}
        DOCKER_BUILDKIT: 1
      shell: bash
      run: |
        docker build \
          --build-arg GITHUB_TOKEN=${{ inputs.backfeed-repo-token }} \
          --secret id=npm,src=$NPM_CONFIG_USERCONFIG \
          -t ${IMAGE}:${{ github.sha }} -t ${IMAGE}:${VERSION} \
          -f Dockerfile .
        docker push ${IMAGE}:${{ github.sha }}
        docker push ${IMAGE}:${VERSION}
