name: 'Docker build action'
description: 'Odyssey docker build image action'
inputs:
  image-name:
    description: "Name of the docker image, defaults to git repository name"
    required: true
    default: ${{ github.event.repository.name }}
  registry-server:
    description: "Docker registry location/URL"
    required: true
  registry-user:
    description: "Docker registry username"
    required: true
  registry-pass:
    description: "Docker registry password"
    required: true
  npm-token:
    required: false
    description: "Access token for private (npm) packages."
  backfeed-repo-token:
    required: false
    description: "Github token to passthrough docker build to access current repo"
  github-token:
    required: false
    description: "Github token. Used tyo login to ghcr.io"
outputs:
  version:
    description: "Version string generated for the image."
    value: ${{ steps.setvars.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: setvars
      name: ${{github.event_name}}-${{github.event.ref }}
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "schedule" ]; then
          VERSION=nightly
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        elif [[ $GITHUB_REF == refs/heads/release/* ]]; then
          VERSION="release"
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          VERSION=pr-${{ github.event.number }}
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "::set-output name=version::$(echo $VERSION)"

    # checkout the repo
    - name: "Checkout GitHub Action"
      uses: actions/checkout@master
      with:
        submodules: true
        lfs: true

    - name: "Github packages authorization"
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
      run: |
        echo "@OdysseyMomentumExperience:registry=https://npm.pkg.github.com/" > $HOME/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc

    - name: "Build image"
      env:
        AZURE_IMAGE: ${{ inputs.registry-server }}/${{ inputs.image-name }}
        GITHUB_IMAGE: ghcr.io/momentum-xyz/${{ inputs.image-name }}
        DOCKER_BUILDKIT: 1
      shell: bash
      run: |
        GIT_DESC=$(git describe || echo "${{github.sha}}")
        docker build \
          --build-arg GITHUB_TOKEN=${{ inputs.backfeed-repo-token }} \
          --secret id=npm,src=$HOME/.npmrc \
          --tag ${AZURE_IMAGE}:${GIT_DESC} --tag ${AZURE_IMAGE}:${VERSION} \
          --tag ${GITHUB_IMAGE}:${GIT_DESC} --tag ${GITHUB_IMAGE}:${VERSION} \
          --file Dockerfile .

    - name: "Azure Docker login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.registry-server }}
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-pass }}

    - name: "Push image to Azure"
      env:
        IMAGE: ${{ inputs.registry-server }}/${{ inputs.image-name }}
      shell: bash
      run: |
        GIT_DESC=$(git describe || echo "${{github.sha}}")
        docker push ${IMAGE}:${GIT_DESC}
        docker push ${IMAGE}:${VERSION}

    - name: "Github Docker login"
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: "Push image to Github"
      env:
        IMAGE: ghcr.io/momentum-xyz/${{ inputs.image-name }}
      shell: bash
      run: |
        GIT_DESC=$(git describe || echo "${{github.sha}}")
        docker push ${IMAGE}:${GIT_DESC}
        docker push ${IMAGE}:${VERSION}